GET http://localhost:80/api/item?id=99
Accept: application/json

###
POST http://localhost:8080/api/projects
Content-Type: application/json

{
  "title": "a",
  "description": "a",
  "owner": "a",
  "url": "a",
  "imageSrcs": [
    "a"
  ],
  "tagNames": [
    "Tag1", "Tag2"
  ]
}

###
GET http://localhost:8080/api/projects
Accept: application/json

###

GET http://localhost:8080/api/projects/find?searchQuery=A
Accept: application/json

###

GET http://localhost:8080/api/projects/1
Accept: application/json

