POST http://localhost:8080/api/projects/add
Content-Type: application/json

{
  "title": "TestTitle",
  "description": "TestDescription",
  "owner": "TestOwner",
  "url": "TestURL"
}

###
GET http://localhost:8080/api/projects/all
Accept: application/json

###

